# Site settings
title: Jellever
email: jelle@jellever.be
author: Jelle Vermandere
description:
url:
# Social icons
show_social_icons: true
username: jellevermandere


# Build settings

collections:
  games:
    output: true

  visualisations:
    output: true

defaults:
  -
    scope:
      type: "games"
    values:
      layout: "game"
      
  -
    scope:
      type: "visualisations"
    values:
      layout: "visualisation"
      permalink: /visualisations/:title




# sass

sass:
  sass_dir: css
